### PR TITLE
activity: add mokee platlogo

### PR DESCRIPTION
**Pull request by NoelMacwan**
why dont we have that :o

### CODE REVIEW

**Comment by Ryuinferno** [comment]
Where's the drawable? And there are errors in the code, you didn't modify completely

**Comment by Ryuinferno** [comment]
And again, please use gerrit, we won't merge it here anyway

**Comment by NoelMacwan** [comment]
@Ryuinferno , drawable is coming soon 
and can you tell me errors ?

**Comment by Ryuinferno** [comment]
mIsCM

If you tested the code you would have known...

**Comment by NoelMacwan** [comment]
okay , i got it 
@Ryuinferno well can i use pull request for fixing this and adding drawable , next time ill use gerrit

**Pull request closed without merging**
